"""
Django settings for SkillSpace project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件（项目根目录，backend/ 的上一级）
# settings.py 在 backend/SkillSpace/settings.py
# 所以需要往上两级找到项目根目录
PROJECT_ROOT = BASE_DIR.parent  # /home/huazhu/MySkillSpace
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

# Add myapps directory to Python path
sys.path.insert(0, os.path.join(BASE_DIR, "SkillSpace", "myapps"))


# 输出sys.path都有哪些路径
# print("系统路径path:",sys.path)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"  # 从环境变量读取，默认为 True（开发环境）

# ALLOWED_HOSTS - 从环境变量读取，支持逗号分隔的多个主机
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    # admin 界面美化
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",  # Channels ASGI 服务器（必须放在staticfiles前面）
    "django.contrib.staticfiles",
    # 第三方应用
    "channels",  # WebSocket 支持
    "rest_framework",
    "corsheaders",
    # myapps
    "tasks_hub",
    "resume",
    "auth_system",  # 用户认证系统
    "ai_demo",  # 人工智能Demo
    "monitor",  # 系统监控
]

MIDDLEWARE = [
    # 放在最前面-跨域问题
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # 启用CSRF保护
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 操作日志中间件 - 记录所有API操作
    "auth_system.middleware.OperationLogMiddleware",
]
# CORS配置：仅允许指定来源（不使用 CORS_ALLOW_ALL_ORIGINS）
CORS_ALLOWED_ORIGINS = [
    # vite默认接口
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # WSL2 IP 地址（172.26.x.x 段）
    "http://172.26.206.220:5173",
]

# 允许携带 Cookie (Session 认证必须)
CORS_ALLOW_CREDENTIALS = True

# Session 配置
SESSION_COOKIE_AGE = 86400  # Session过期时间（24小时）
SESSION_COOKIE_HTTPONLY = True  # 防止JavaScript访问
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF保护
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都更新Session

# CSRF 配置
CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript读取CSRF token
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    # WSL2 IP 地址（172.26.x.x 段）
    "http://172.26.206.220:5173",
]

ROOT_URLCONF = "SkillSpace.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SkillSpace.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv("DB_NAME"):  # 如果配置了数据库名，使用配置的数据库（PostgreSQL）
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
            "NAME": os.getenv("DB_NAME", ""),
            "USER": os.getenv("DB_USER", ""),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:  # CI 环境或未配置数据库，使用 SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

# 使用国际化
USE_I18N = True
# 使用时区
USE_TZ = True

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        # 允许所有用户访问
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 会话认证
        "rest_framework.authentication.SessionAuthentication",
        # 基本认证
        "rest_framework.authentication.BasicAuthentication",
    ],
    # 分页配置
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # 默认每页数量
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# 开发环境静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files (用户上传文件)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ========== CELERY 配置 ==========
# Celery Broker (使用 RabbitMQ)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "amqp://guest:guest@localhost:5672//")

# ========== Result Backend 配置 ==========
# 使用 Redis 存储任务结果
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://:123456@localhost:6379/0")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30分钟超时
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # ✅ 改为 1（重要！）
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50  # ✅ 新增：每50个任务重启Worker

# ========== 邮件配置（用于测试）==========
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # 控制台打印邮件（安全！）
DEFAULT_FROM_EMAIL = "noreply@skillspace.local"  # 设置默认发件人


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========== 自定义用户模型配置 ==========
# 指定自定义的User模型
AUTH_USER_MODEL = "auth_system.User"

# 关闭底部 "Simple UI 官方文档" 链接
SIMPLEUI_HOME_INFO = False
# 关闭更新提示
SIMPLEUI_VERSION = False

# 配置 CSRF 可信源（关键：添加前端地址）
# 注意，CSRF中间件要启动（非注释状态）
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # 你的前端地址
    "http://127.0.0.1:5173",  # 可选，防止IP访问的情况
    "http://172.26.206.220:5173",  # WSL2 IP 地址
]

# ========== Django Channels 配置 ==========
# 指定 ASGI 应用（取代 WSGI）
ASGI_APPLICATION = "SkillSpace.asgi.application"

# Channel Layer 配置（开发环境使用内存，生产环境使用 Redis）
if DEBUG:
    # 开发环境：使用内存通道层（不需要Redis）
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}
else:
    # 生产环境：使用 Redis 作为消息传输层
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": f"redis://:{os.getenv('REDIS_PASSWORD', '123456')}@{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/1",
                    }
                ],
                "capacity": 1500,  # 每个 channel 最大消息数
                "expiry": 10,  # 消息过期时间（秒）
            },
        },
    }


# AI 阿里云大模型
# ================= 配置区域 =================
# 阿里云百炼的兼容 Base URL
