# Generated by Django 5.2.8 on 2025-11-30 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='用户登录时使用的邮箱地址', max_length=255, unique=True, verbose_name='邮箱地址')),
                ('username', models.CharField(blank=True, help_text='用户显示名称，可以为空', max_length=150, null=True, verbose_name='用户名')),
                ('is_active', models.BooleanField(default=True, help_text='取消选择代替删除账户', verbose_name='账户激活状态')),
                ('is_staff', models.BooleanField(default=False, help_text='指定用户是否可以登录管理后台', verbose_name='管理员状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='用户首次创建账户的时间', verbose_name='注册时间')),
                ('oauth_provider', models.CharField(blank=True, choices=[('google', 'Google'), ('github', 'GitHub')], help_text='第三方登录平台（如Google、GitHub）', max_length=50, null=True, verbose_name='OAuth提供商')),
                ('oauth_id', models.CharField(blank=True, help_text='第三方平台返回的用户唯一标识', max_length=255, null=True, verbose_name='OAuth用户ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'auth_user',
                'ordering': ['-date_joined'],
            },
        ),
    ]
