# Generated by Django 4.2.27 on 2025-12-08 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], default='C', max_length=1, verbose_name='菜单类型')),
                ('perms', models.CharField(blank=True, help_text='如 system:user:list', max_length=100, null=True, verbose_name='权限标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='auth_system.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '系统菜单',
                'verbose_name_plural': '系统菜单',
                'db_table': 'sys_menu',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(help_text='如 admin, common', max_length=100, unique=True, verbose_name='角色权限字符')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, db_table='sys_role_menu', to='auth_system.menu', verbose_name='拥有菜单')),
            ],
            options={
                'verbose_name': '系统角色',
                'verbose_name_plural': '系统角色',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='邮箱地址')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='用户名')),
                ('avatar', models.CharField(blank=True, default='default.jpg', max_length=255, null=True, verbose_name='头像')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, db_table='sys_user_role', to='auth_system.role', verbose_name='拥有角色')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'sys_user',
                'ordering': ['-date_joined'],
            },
        ),
    ]
