# Generated by Django 5.2.10 on 2026-01-10 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='登录账号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='登录IP')),
                ('login_location', models.CharField(blank=True, max_length=100, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('device', models.CharField(blank=True, max_length=50, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('0', '成功'), ('1', '失败')], max_length=1, verbose_name='登录状态')),
                ('msg', models.CharField(blank=True, max_length=255, verbose_name='提示信息')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'sys_login_log',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='sys_login_l_login_t_ee1a41_idx'), models.Index(fields=['username', '-login_time'], name='sys_login_l_usernam_e0c2de_idx'), models.Index(fields=['status', '-login_time'], name='sys_login_l_status_82da78_idx')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=255, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], default='C', max_length=1, verbose_name='菜单类型')),
                ('perms', models.CharField(blank=True, help_text='如 system:user:list', max_length=100, null=True, verbose_name='权限标识')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='auth_system.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '系统菜单',
                'verbose_name_plural': '系统菜单',
                'db_table': 'sys_menu',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(help_text='如 admin, common', max_length=100, unique=True, verbose_name='角色权限字符')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, db_table='sys_role_menu', to='auth_system.menu', verbose_name='拥有菜单')),
            ],
            options={
                'verbose_name': '系统角色',
                'verbose_name_plural': '系统角色',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='邮箱地址')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='用户名')),
                ('avatar', models.CharField(blank=True, default='default.jpg', max_length=255, null=True, verbose_name='头像')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('plain_password', models.CharField(blank=True, help_text='⚠️ 仅开发环境使用，用于调试。生产环境请删除此字段！', max_length=128, null=True, verbose_name='明文密码')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, db_table='sys_user_role', to='auth_system.role', verbose_name='拥有角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'sys_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='操作账号')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(choices=[('新增', '新增'), ('修改', '修改'), ('删除', '删除'), ('查询', '查询'), ('导出', '导出'), ('导入', '导入'), ('登录', '登录'), ('登出', '登出'), ('其他', '其他')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='请求URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='浏览器')),
                ('request_params', models.TextField(blank=True, verbose_name='请求参数')),
                ('response_data', models.TextField(blank=True, verbose_name='响应数据')),
                ('status', models.CharField(choices=[('0', '成功'), ('1', '失败')], default='0', max_length=1, verbose_name='操作状态')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('duration', models.IntegerField(default=0, verbose_name='执行时长(ms)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sys_operati_created_3dfe04_idx'), models.Index(fields=['user', '-created_at'], name='sys_operati_user_id_502c01_idx'), models.Index(fields=['module', '-created_at'], name='sys_operati_module_6b2cfc_idx')],
            },
        ),
    ]
