# Generated by Django 4.2.27 on 2025-12-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, help_text='⚠️ 仅开发环境使用，用于调试。生产环境请删除此字段！', max_length=128, null=True, verbose_name='明文密码'),
        ),
    ]
