# Generated by Django 5.2.8 on 2025-12-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='用户显示名称，可用于登录', max_length=150, null=True, verbose_name='用户名'),
        ),
    ]
