# Generated by Django 4.2.27 on 2025-12-15 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_user_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='登录账号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='登录IP')),
                ('login_location', models.CharField(blank=True, max_length=100, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('device', models.CharField(blank=True, max_length=50, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('0', '成功'), ('1', '失败')], max_length=1, verbose_name='登录状态')),
                ('msg', models.CharField(blank=True, max_length=255, verbose_name='提示信息')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'sys_login_log',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='sys_login_l_login_t_ee1a41_idx'), models.Index(fields=['username', '-login_time'], name='sys_login_l_usernam_e0c2de_idx'), models.Index(fields=['status', '-login_time'], name='sys_login_l_status_82da78_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='操作账号')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(choices=[('新增', '新增'), ('修改', '修改'), ('删除', '删除'), ('查询', '查询'), ('导出', '导出'), ('导入', '导入'), ('登录', '登录'), ('登出', '登出'), ('其他', '其他')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='请求URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='浏览器')),
                ('request_params', models.TextField(blank=True, verbose_name='请求参数')),
                ('response_data', models.TextField(blank=True, verbose_name='响应数据')),
                ('status', models.CharField(choices=[('0', '成功'), ('1', '失败')], default='0', max_length=1, verbose_name='操作状态')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('duration', models.IntegerField(default=0, verbose_name='执行时长(ms)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sys_operati_created_3dfe04_idx'), models.Index(fields=['user', '-created_at'], name='sys_operati_user_id_502c01_idx'), models.Index(fields=['module', '-created_at'], name='sys_operati_module_6b2cfc_idx')],
            },
        ),
    ]
