# Generated by Django 4.2.27 on 2025-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='任务ID')),
                ('task_type', models.CharField(choices=[('file', '文件处理'), ('data', '数据获取'), ('email', '邮件发送')], max_length=10, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('success', '成功'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '异步任务',
                'verbose_name_plural': '异步任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
