# Generated by Django 5.2.8 on 2025-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctask',
            options={'ordering': ['-created_at'], 'verbose_name': '异步任务', 'verbose_name_plural': '异步任务'},
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('success', '成功'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='task_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='asynctask',
            name='task_type',
            field=models.CharField(choices=[('file', '文件处理'), ('data', '数据获取'), ('email', '邮件发送')], max_length=10, verbose_name='任务类型'),
        ),
    ]
