# Generated by Django 5.2.10 on 2026-01-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='任务唯一标识', max_length=100, unique=True)),
                ('celery_task_id', models.CharField(db_index=True, help_text='Celery任务ID', max_length=100)),
                ('session_id', models.CharField(db_index=True, help_text='会话ID', max_length=100)),
                ('prompt', models.TextField(help_text='用户提问')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', help_text='任务状态', max_length=20)),
                ('ws_url', models.CharField(help_text='WebSocket连接地址', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('error_message', models.TextField(blank=True, help_text='错误信息')),
            ],
            options={
                'verbose_name': 'AI任务',
                'verbose_name_plural': 'AI任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='会话ID，用于区分不同用户的对话', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI')], help_text='角色', max_length=20)),
                ('content', models.TextField(help_text='对话内容')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='是否隐藏此记录（软删除）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'ordering': ['created_at'],
            },
        ),
    ]
