# Generated by Django 4.2.27 on 2025-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的名字', max_length=100, verbose_name='姓名')),
                ('position', models.CharField(default='我的职位', max_length=100, verbose_name='职位')),
                ('education', models.TextField(default='教育背景', verbose_name='教育经历')),
                ('experience', models.TextField(default='工作经验', verbose_name='工作经验')),
                ('skills', models.TextField(default='技能列表', verbose_name='技能')),
            ],
            options={
                'verbose_name': '简历条目',
                'verbose_name_plural': '简历条目',
            },
        ),
    ]
