# Generated by Django 5.2.8 on 2025-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.PositiveIntegerField(help_text='18-65岁', verbose_name='年龄')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('work_years', models.PositiveIntegerField(help_text='0-20年', verbose_name='工作年限')),
                ('hometown', models.CharField(max_length=200, verbose_name='籍贯')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.AlterModelOptions(
            name='resumeitem',
            options={'ordering': ['section', 'order', 'skill_order'], 'verbose_name': '简历条目', 'verbose_name_plural': '简历条目'},
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='skill_order',
            field=models.PositiveIntegerField(default=0, verbose_name='技能序号'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
