# Generated by Django 5.2.8 on 2025-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_personalinfo_alter_resumeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='工作成果'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='获取时间'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='company_description',
            field=models.TextField(blank=True, verbose_name='公司描述'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='degree',
            field=models.CharField(blank=True, choices=[('high_school', '高中'), ('junior_college', '专科'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级'), ('expert', '专家')], max_length=20, verbose_name='熟练程度'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, verbose_name='副标题'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
