# Generated by Django 5.2.8 on 2025-11-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resumeitem_achievements_resumeitem_acquisition_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.AlterModelOptions(
            name='resumeitem',
            options={'ordering': ['section', 'order'], 'verbose_name': '简历条目', 'verbose_name_plural': '简历条目'},
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='major',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='skill_order',
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='start_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
