# Generated by Django 5.2.8 on 2025-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_delete_personalinfo_alter_resumeitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeitem',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='resumeitem',
            options={'verbose_name': '简历条目', 'verbose_name_plural': '简历条目'},
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='resumeitem',
            name='title',
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='education',
            field=models.TextField(default='教育背景', verbose_name='教育经历'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='experience',
            field=models.TextField(default='工作经验', verbose_name='工作经验'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='name',
            field=models.CharField(default='我的名字', max_length=100, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='position',
            field=models.CharField(default='我的职位', max_length=100, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='skills',
            field=models.TextField(default='技能列表', verbose_name='技能'),
        ),
        migrations.DeleteModel(
            name='ResumeSection',
        ),
    ]
